<?
$weAreIn=  str_replace("/setup.php", "", $_SERVER["REQUEST_URI"]);
function full_url(){
    $s = empty($_SERVER["HTTPS"]) ? '' : ($_SERVER["HTTPS"] == "on") ? "s" : "";
    $protocol = substr(strtolower($_SERVER["SERVER_PROTOCOL"]), 0, strpos(strtolower($_SERVER["SERVER_PROTOCOL"]), "/")) . $s;
    $port = ($_SERVER["SERVER_PORT"] == "80") ? "" : (":".$_SERVER["SERVER_PORT"]);
    return $protocol . "://" . $_SERVER['SERVER_NAME'] . $port . $_SERVER['REQUEST_URI'];
}
$actual_link = full_url();
//$rootFolder=

?>
<h1>Hello you...</h1>
<em>This is not yet the "hello world" step</em>

<h3>
    1/ At the end the of the .htaccess file paste the following lines :
</h3>
<code>
    #-----------------------------------------------------------------</br>
    #The following lines have been generated by <?=$actual_link?>.</br> 
    #It assumes that we are in <?=$weAreIn?> folder.</br>
    RewriteBase <?=$weAreIn?></br>
    RewriteRule ^setup.php$ setup.php?rootFolder=<?=$weAreIn?> [L,QSA]</br>
    RewriteCond %{REQUEST_FILENAME} !-f</br>
    RewriteRule ^(.*)$ index.php?route=$1&rootFolder=<?=$weAreIn?> [L,QSA]</br>
    #-----------------------------------------------------------------</br>
</code>
<h3>
    2/ Upload the .htaccess file...
</h3>
<h3>
    3/ Directories configuration :
</h3>
<?

require_once '_system/Boot.php'; // the same...
echo Boot::testConfig();
?>

